[package]
name = "terraphim_tui"
version = "0.1.0"
edition = "2021"

[features]
default = []
repl = ["dep:rustyline", "dep:colored", "dep:comfy-table", "dep:indicatif", "dep:dirs"]
repl-full = ["repl", "repl-chat", "repl-mcp"]
repl-chat = ["repl"]  # Chat functionality
repl-mcp = ["repl"]   # MCP tools integration

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
ratatui = "0.28"
crossterm = "0.27"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
log = "0.4"
jiff = "0.1"
urlencoding = "2.1"

# REPL dependencies - only compiled with features
rustyline = { version = "14.0", optional = true }
colored = { version = "3.0", optional = true }
comfy-table = { version = "7.0", optional = true }
indicatif = { version = "0.17", optional = true }
dirs = { version = "5.0", optional = true }

terraphim_types = { path = "../terraphim_types" }
terraphim_settings = { path = "../terraphim_settings" }
terraphim_persistence = { path = "../terraphim_persistence" }
terraphim_config = { path = "../terraphim_config" }
terraphim_automata = { path = "../terraphim_automata" }
terraphim_service = { path = "../terraphim_service" }
terraphim_middleware = { path = "../terraphim_middleware" }
terraphim_rolegraph = { path = "../terraphim_rolegraph" }

[dev-dependencies]
serial_test = "3.0"
futures = "0.3"
portpicker = "0.1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "terraphim-tui"
path = "src/main.rs"

[package.metadata.deb]
maintainer = "Terraphim Contributors <team@terraphim.ai>"
copyright = "2024, Terraphim Contributors"
license-file = ["../../LICENSE", "4"]
extended-description = """
Terraphim TUI - Terminal User Interface for Terraphim AI.
Command-line interface with interactive REPL and ASCII graph visualization.
Supports search, configuration management, and data exploration."""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/terraphim-tui", "usr/bin/", "755"],
    ["../../README.md", "usr/share/doc/terraphim-tui/README", "644"],
]
