version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "terraphim/maintainers"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore patch updates for core dependencies to reduce noise
      - dependency-name: "serde*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "tokio*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "reqwest"
        update-types: ["version-update:semver-patch"]
      # Pin problematic dependencies to prevent unstable Rust features
      - dependency-name: "wiremock"
        versions: ["0.6.5"]
      # Pin to avoid breaking changes that require code migration
      - dependency-name: "schemars"
        versions: [">= 1.0.0"]
      - dependency-name: "thiserror"
        versions: [">= 2.0.0"]

  # npm dependencies for desktop frontend
  - package-ecosystem: "npm"
    directory: "/desktop"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "terraphim/maintainers"
    labels:
      - "dependencies"
      - "frontend"
      - "nodejs"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore patch updates for stable packages
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "terraphim/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "terraphim/maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
