# These are supported funding platforms
# GitHub Sponsors: https://github.com/sponsors
# Open Collective: https://opencollective.com
# Ko-fi: https://ko-fi.com/
# Tidelift: https://tidelift.com/
# Community Bridge: https://funding.communitybridge.org
# Issuehunt: https://issuehunt.io/
# Otechie: https://otechie.com/
# Custom: https://example.com

github: [terraphim]
open_collective: terraphim
ko_fi: terraphim
