#[cfg(feature = "ai-assistant")]
pub mod ai_assistant;
pub mod clickup;
#[cfg(feature = "grepapp")]
pub mod grep_app;
#[cfg(feature = "jmap")]
pub mod jmap;
pub mod mcp;
pub mod perplexity;
pub mod query_rs;
pub mod quickwit;
#[cfg(feature = "ai-assistant")]
pub use ai_assistant::AiAssistantHaystackIndexer;
pub use clickup::ClickUpHaystackIndexer;
#[cfg(feature = "grepapp")]
pub use grep_app::GrepAppHaystackIndexer;
#[cfg(feature = "jmap")]
pub use jmap::JmapHaystackIndexer;
pub use mcp::McpHaystackIndexer;
pub use perplexity::PerplexityHaystackIndexer;
pub use query_rs::QueryRsHaystackIndexer;
pub use quickwit::QuickwitHaystackIndexer;
