#[cfg(feature = "ai-assistant")]
pub mod ai_assistant;
#[cfg(feature = "atomic")]
pub mod atomic;
pub mod clickup;
#[cfg(feature = "grepapp")]
pub mod grep_app;
pub mod mcp;
pub mod perplexity;
pub mod query_rs;
#[cfg(feature = "ai-assistant")]
pub use ai_assistant::AiAssistantHaystackIndexer;
#[cfg(feature = "atomic")]
pub use atomic::AtomicHaystackIndexer;
pub use clickup::ClickUpHaystackIndexer;
#[cfg(feature = "grepapp")]
pub use grep_app::GrepAppHaystackIndexer;
pub use mcp::McpHaystackIndexer;
pub use perplexity::PerplexityHaystackIndexer;
pub use query_rs::QueryRsHaystackIndexer;
