#!/usr/bin/env python3
"""Generate Rust data tables for terraphim_megahal from the vendored Ruby sources.

Reads `scripts/ruby_vendor/lib/megahal/keyword.rb` and the personality files and
emits:
  - `src/keyword_data.rs`  (GREETING, ANTONYMS, AUXILIARY, BANNED constants)
  - `src/personalities_data/<name>.txt` (training corpora, one sentence per line)

Run from the crate root:

    python3 scripts/extract_data.py

The vendored Ruby sources are Unlicense (public domain), from
https://github.com/kranzky/megahal. Re-run this script only when re-vendoring
an updated upstream; the generated artefacts are committed.
"""

from __future__ import annotations

import re
from pathlib import Path

CRATE = Path(__file__).resolve().parent.parent
VENDOR = CRATE / "scripts" / "ruby_vendor" / "lib" / "megahal"


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def extract_heredoc(text: str, marker: str) -> list[str]:
    """Extract the lines of a `<<-MARKER ... MARKER` heredoc."""
    lines = text.splitlines()
    out: list[str] = []
    inside = False
    for line in lines:
        if not inside and f"<<-{marker}" in line:
            inside = True
            continue
        if inside:
            if line.strip() == marker:
                break
            out.append(line.strip())
    return [line for line in out if line]


def extract_ruby_array(text: str, name: str) -> list[str]:
    """Extract a literal Ruby array such as GREETING = [...] (strings only)."""
    match = re.search(name + r"\s*=\s*(\[[^\]]*\])", text, re.S)
    assert match, f"array {name} not found"
    return re.findall(r'"([^"]*)"', match.group(1))


def extract_antonym_pairs(text: str) -> list[tuple[str, str]]:
    match = re.search(r"ANTONYMS\s*=\s*\[(.*?)\n\s*\]", text, re.S)
    assert match, "ANTONYMS not found"
    words = re.findall(r'"([^"]*)"', match.group(1))
    assert len(words) % 2 == 0, "ANTONYMS must be pairs"
    return [(words[i], words[i + 1]) for i in range(0, len(words), 2)]


def main() -> None:
    keyword_rb = (VENDOR / "keyword.rb").read_text(encoding="utf-8")

    greeting = extract_ruby_array(keyword_rb, "GREETING")
    antonyms = extract_antonym_pairs(keyword_rb)
    auxiliary = extract_heredoc(keyword_rb, "EOS")
    banned = re.findall(
        r"BANNED\s*=\s*<<-EOS.*?\n(.*?)\n\s*EOS", keyword_rb, re.S
    )[0].splitlines()
    banned = [line.strip() for line in banned if line.strip()]

    # Sanity: heredoc extraction must agree for both lists.
    assert "DISLIKE" in auxiliary and "YOURSELF" in auxiliary
    assert "A" in banned and "YET" in banned

    out = Path(__file__).resolve().parent.parent / "src" / "keyword_data.rs"
    lines: list[str] = [
        "// GENERATED by scripts/extract_data.py from scripts/ruby_vendor/lib/megahal/keyword.rb",
        "// (upstream MegaHAL gem, Unlicense). Do not edit by hand; re-run the script",
        "// after re-vendoring upstream.",
        "",
    ]

    lines.append(f"pub const GREETING: [&str; {len(greeting)}] = [")
    lines.extend(f"    {rust_str(w)}," for w in greeting)
    lines.append("];")
    lines.append("")

    lines.append(f"pub const ANTONYMS: [(&str, &str); {len(antonyms)}] = [")
    lines.extend(f"    ({rust_str(a)}, {rust_str(b)})," for a, b in antonyms)
    lines.append("];")
    lines.append("")

    lines.append(f"pub const AUXILIARY: [&str; {len(auxiliary)}] = [")
    lines.extend(f"    {rust_str(w)}," for w in auxiliary)
    lines.append("];")
    lines.append("")

    lines.append(f"pub const BANNED: [&str; {len(banned)}] = [")
    lines.extend(f"    {rust_str(w)}," for w in banned)
    lines.append("];")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(greeting)} greetings, {len(antonyms)} antonym pairs, "
          f"{len(auxiliary)} auxiliary, {len(banned)} banned)")

    # Personality corpora.
    dest = CRATE / "src" / "personalities_data"
    dest.mkdir(exist_ok=True)
    for path in sorted(VENDOR.glob("personalities/*.rb")):
        name = path.stem
        text = path.read_text(encoding="utf-8")
        match = re.search(r'add_personality\(:(\w+),\s*<<-EOP\)\n(.*?)\nEOP', text, re.S)
        assert match, f"personality corpus not found in {path}"
        assert match.group(1) == name
        corpus = match.group(2)
        # Upstream _train strips each line; store stripped, non-empty lines only
        # (blank lines would be dropped by the learning guard anyway).
        cleaned = "\n".join(
            line.strip() for line in corpus.splitlines() if line.strip()
        )
        target = dest / f"{name}.txt"
        target.write_text(cleaned + "\n", encoding="utf-8")
        print(f"wrote {target} ({len(cleaned.splitlines())} lines)")


if __name__ == "__main__":
    main()
