/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function replaceLinks(content: string, thesaurus: string): Promise<string>
export declare function getConfig(): Promise<string>
