/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function replaceLinks(content: string, thesaurus: string): string
export declare function getTestConfig(): Promise<string>
export declare function getConfig(): Promise<string>
export declare function searchDocumentsSelectedRole(query: string): Promise<string>
/** Result type for autocomplete operations */
export interface AutocompleteResult {
  term: string
  normalizedTerm: string
  id: number
  url?: string
  score: number
}
/** Build an autocomplete index from a JSON thesaurus string */
export declare function buildAutocompleteIndexFromJson(thesaurusJson: string): Array<number>
/** Search the autocomplete index with a query */
export declare function autocomplete(indexBytes: Buffer, query: string, maxResults?: number | undefined | null): Array<AutocompleteResult>
/** Fuzzy search with Jaro-Winkler similarity (placeholder - to be implemented) */
export declare function fuzzyAutocompleteSearch(indexBytes: Buffer, query: string, threshold?: number | undefined | null, maxResults?: number | undefined | null): Array<AutocompleteResult>
/** Result type for knowledge graph operations */
export interface GraphStats {
  nodeCount: number
  edgeCount: number
  documentCount: number
  thesaurusSize: number
  isPopulated: boolean
}
/** Result for graph query operations */
export interface GraphQueryResult {
  documentId: string
  rank: number
  tags: Array<string>
  nodes: Array<string>
  title: string
  url: string
}
/** Build a role graph from JSON thesaurus data */
export declare function buildRoleGraphFromJson(roleName: string, thesaurusJson: string): Array<number>
/** Check if all terms found in the text are connected by paths in the role graph */
export declare function areTermsConnected(graphBytes: Buffer, text: string): boolean
/** Query the role graph for documents matching the search terms */
export declare function queryGraph(graphBytes: Buffer, queryString: string, offset?: number | undefined | null, limit?: number | undefined | null): Array<GraphQueryResult>
/** Get statistics about the role graph */
export declare function getGraphStats(graphBytes: Buffer): GraphStats
/** Get version information */
export declare function version(): string
