"""Type stubs for terraphim_rolegraph."""

from typing import Dict, List, Optional, Set, Tuple

__version__: str

class Node:
    """A node in the knowledge graph representing a single concept."""

    @property
    def id(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def connected_with(self) -> Set[int]: ...

class Edge:
    """An edge in the knowledge graph connecting two concepts."""

    @property
    def id(self) -> int: ...
    @property
    def rank(self) -> int: ...
    @property
    def doc_hash(self) -> Dict[str, int]: ...

class IndexedDocument:
    """An indexed document with graph metadata."""

    @property
    def id(self) -> str: ...
    @property
    def matched_edges(self) -> List[Edge]: ...
    @property
    def rank(self) -> int: ...
    @property
    def tags(self) -> List[str]: ...
    @property
    def nodes(self) -> List[int]: ...

class Document:
    """A document to insert into the knowledge graph."""

    id: str
    url: str
    title: str
    body: str
    description: Optional[str]
    tags: Optional[List[str]]
    rank: Optional[int]

    def __init__(
        self,
        id: str,
        url: str,
        title: str,
        body: str,
        description: Optional[str] = None,
        tags: Optional[List[str]] = None,
        rank: Optional[int] = None,
    ) -> None: ...

class GraphStats:
    """Statistics about the graph structure."""

    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def document_count(self) -> int: ...
    @property
    def thesaurus_size(self) -> int: ...
    @property
    def is_populated(self) -> bool: ...

class LogicalOperator:
    """Logical operator for combining search terms."""

    And: "LogicalOperator"
    Or: "LogicalOperator"

class RoleGraph:
    """A knowledge graph for a specific role."""

    def __init__(self, role_name: str, thesaurus_json: str) -> None: ...
    @property
    def role(self) -> str: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

    # Document methods
    def insert_document(self, document_id: str, document: Document) -> None: ...
    def has_document(self, document_id: str) -> bool: ...
    def get_document(self, document_id: str) -> Optional[IndexedDocument]: ...
    def get_all_documents(self) -> List[Tuple[str, IndexedDocument]]: ...
    def document_count(self) -> int: ...
    def find_document_ids_for_term(self, term: str) -> List[str]: ...

    # Query methods
    def find_matching_node_ids(self, text: str) -> List[int]: ...
    def is_all_terms_connected_by_path(self, text: str) -> bool: ...
    def query_graph(
        self,
        query_string: str,
        offset: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> List[Tuple[str, IndexedDocument]]: ...
    def query_graph_with_operators(
        self,
        search_terms: List[str],
        operator: LogicalOperator,
        offset: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> List[Tuple[str, IndexedDocument]]: ...

    # Stats methods
    def get_node_count(self) -> int: ...
    def get_edge_count(self) -> int: ...
    def get_document_count(self) -> int: ...
    def is_graph_populated(self) -> bool: ...
    def get_graph_stats(self) -> GraphStats: ...
    def validate_documents(self) -> List[str]: ...

    # Inspection methods
    def nodes_map(self) -> Dict[int, Node]: ...
    def edges_map(self) -> Dict[int, Edge]: ...

    # Serialization
    def to_json(self) -> str: ...
    def to_json_pretty(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> "RoleGraph": ...

def magic_pair(x: int, y: int) -> int:
    """Combine two node IDs into a unique edge ID using elegant pairing."""
    ...

def magic_unpair(z: int) -> Tuple[int, int]:
    """Reverse an edge ID back into two node IDs."""
    ...

def split_paragraphs(text: str) -> List[str]:
    """Split text into paragraphs using unicode sentence boundary detection."""
    ...
