server_hostname = "127.0.0.1:8000"
api_endpoint="http://localhost:8000/api"
initialized = "${TERRAPHIM_INITIALIZED:-false}"
default_data_path = "${TERRAPHIM_DATA_PATH:-${HOME}/.terraphim}"

# Non-locking backends for local development
# Note: Directories will be created automatically if they don't exist

[profiles.memory]
type = "memory"

[profiles.dashmap]
type = "dashmap"
root = "/tmp/terraphim_dashmap"  # Directory auto-created

[profiles.sqlite]
type = "sqlite"
datadir = "/tmp/terraphim_sqlite"  # Directory auto-created

[profiles.redb]
type = "redb"
datadir = "/tmp/terraphim_redb/terraphim.redb"  # Directory for redb database
table = "terraphim"  # Required table name for redb
