global_shortcut = "Ctrl+/"
default_role = "Default"
id = "01HK54A3TQ55ZRJ306TYD7J5G8"

[roles.Default]
shortname = "Default"
name = "Default"
relevance_function = "terraphim-graph"
theme = "spacelab"
serverUrl = "http://localhost:8000/articles/search"

[roles.Default.kg]
automata_url = "https://system-operator.s3.eu-west-2.amazonaws.com/term_to_id.json"
kg_type = "markdown"
kg_path = "~/pkm"
public = true
publish = true

[[roles.Default.haystacks]]
haystack = "localsearch"
service = "ripgrep"

[roles.Engineer]
shortname = "Engineer"
name = "Engineer"
relevance_function = "terraphim-graph"
theme = "lumen"
serverUrl = "http://localhost:8000/articles/search"

[roles.Engineer.kg]
automata_url = "https://system-operator.s3.eu-west-2.amazonaws.com/term_to_id.json"
kg_type = "markdown"
kg_path = "~/pkm"
public = true
publish = true

[[roles.Engineer.haystacks]]
haystack = "localsearch"
service = "ripgrep"

[roles."System Operator"]
shortname = "operator"
name = "System Operator"
relevance_function = "terraphim-graph"
theme = "superhero"
serverUrl = "http://localhost:8000/articles/search"

[roles."System Operator".kg]
automata_url = "https://system-operator.s3.eu-west-2.amazonaws.com/term_to_id.json"
kg_type = "markdown"
kg_path = "~/pkm"
public = true
publish = true

[[roles."System Operator".haystacks]]
haystack = "localsearch"
service = "ripgrep"
