//! LLM Types and Request/Response Structures
//!
//! This module contains the common types used for LLM communication,
//! independent of the specific LLM client implementation.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Message roles for LLM communication
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MessageRole {
    /// System-level instruction message
    System,
    /// Message originating from the human user
    User,
    /// Message generated by the AI assistant
    Assistant,
    /// Message produced by a tool invocation
    Tool,
}

/// An individual message in a conversation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmMessage {
    /// Role of the message sender
    pub role: MessageRole,
    /// Text content of the message
    pub content: String,
}

impl LlmMessage {
    /// Create a system-role message
    pub fn system(content: String) -> Self {
        Self {
            role: MessageRole::System,
            content,
        }
    }

    /// Create a user-role message
    pub fn user(content: String) -> Self {
        Self {
            role: MessageRole::User,
            content,
        }
    }

    /// Create an assistant-role message
    pub fn assistant(content: String) -> Self {
        Self {
            role: MessageRole::Assistant,
            content,
        }
    }

    /// Create a tool-role message
    pub fn tool(content: String) -> Self {
        Self {
            role: MessageRole::Tool,
            content,
        }
    }
}

/// Request to an LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmRequest {
    /// Ordered list of messages forming the conversation
    pub messages: Vec<LlmMessage>,
    /// Sampling temperature; higher values produce more varied output
    pub temperature: Option<f32>,
    /// Maximum number of tokens the model may generate
    pub max_tokens: Option<u64>,
    /// Arbitrary key-value metadata attached to the request
    pub metadata: std::collections::HashMap<String, String>,
}

impl LlmRequest {
    /// Create a new request with the given messages and default settings
    pub fn new(messages: Vec<LlmMessage>) -> Self {
        Self {
            messages,
            temperature: None,
            max_tokens: None,
            metadata: std::collections::HashMap::new(),
        }
    }

    /// Set the sampling temperature on this request
    pub fn with_temperature(mut self, temperature: f32) -> Self {
        self.temperature = Some(temperature);
        self
    }

    /// Set the maximum token limit on this request
    pub fn with_max_tokens(mut self, max_tokens: u64) -> Self {
        self.max_tokens = Some(max_tokens);
        self
    }

    /// Attach a metadata key-value pair to this request
    pub fn with_metadata(mut self, key: String, value: String) -> Self {
        self.metadata.insert(key, value);
        self
    }
}

/// Token usage statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Number of tokens in the prompt / input
    pub input_tokens: u64,
    /// Number of tokens generated in the response
    pub output_tokens: u64,
    /// Combined total of input and output tokens
    pub total_tokens: u64,
}

impl TokenUsage {
    /// Create a new `TokenUsage`, computing `total_tokens` automatically
    pub fn new(input_tokens: u64, output_tokens: u64) -> Self {
        Self {
            input_tokens,
            output_tokens,
            total_tokens: input_tokens + output_tokens,
        }
    }

    /// Return a `TokenUsage` with all counts set to zero
    pub fn zero() -> Self {
        Self {
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
        }
    }
}

/// Response from an LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    /// Generated text content from the model
    pub content: String,
    /// Identifier of the model that produced the response
    pub model: String,
    /// Token usage statistics for this response
    pub usage: TokenUsage,
    /// Unique identifier for the originating request
    pub request_id: Uuid,
    /// UTC timestamp when the response was received
    pub timestamp: DateTime<Utc>,
    /// Round-trip duration in milliseconds
    pub duration_ms: u64,
    /// Reason the model stopped generating (e.g. "stop", "length")
    pub finish_reason: String,
}

impl LlmResponse {
    /// Create a minimal `LlmResponse` with the given content and sensible defaults
    pub fn new(content: String) -> Self {
        Self {
            content,
            model: "unknown".to_string(),
            usage: TokenUsage::zero(),
            request_id: Uuid::new_v4(),
            timestamp: Utc::now(),
            duration_ms: 0,
            finish_reason: "completed".to_string(),
        }
    }
}
