[package]
name = "terraphim-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
directories = ">= 2, < 5"
dotenv = "0.15"
config = "0.13.3"
async-once-cell = "0.5.3"
ini = "1.3.0"
toml = "0.8.6"

serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
log = "0.4.14"
test-log = "0.2.14"

[dev-dependencies]
opendal = { version = "0.40.0", features = ["services-dashmap", "services-redis", "services-sled"] }
tempfile = "3.7.1"
