[pack]
# Here you define your AI Pack config
# - It can be packed via `aip pack container_folder`
# - This will create a `namespace-pack_name-v-0-1-0.aipack`
# - It can be installed via `aip install namespace-pack_name-v-0-1-0.aipack`
# Eventually, it can be deployed to aipack.ai with `aip publish container_folder`
# And installed from the repository with `aip install namespace@pack_name`
#

# -- Required Section

# The namespace of this AIPACK.
# Recommendation: Have your username, org name, or "my" if for personal sharing
namespace = "my"

# The pack name
name = "atomic-server-client"

# Version must be semver, `0.1.0` and can have modifiers like `0.1.0-alpha.1`
version = "0.1.0"


# -- Optional section

# license = "MIT or Apache 2"
# homepage = "https://mycoolsite/"
# repo = "https://github.com/cool-org/cool-name"
# author = "Full Name"
# email = "name@email.com"
