[package]
name = "terraphim_it"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
terraphim_automata = { path = "../../crates/terraphim_automata" }
wasm-bindgen-futures = "0.4.1"
[workspace]
resolver = "2"