[package]
name = "terrraphim-automata-wasm"
version = "0.1.0"
authors = ["AlexMikhalev <alex@metacortex.engineer>"]
edition = "2018"

[workspace]
# Empty workspace to prevent workspace inheritance

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"]  }
serde = { version = "1.0", features = ["derive"] }
# serde-wasm-bindgen = "0.5.0"
gloo-utils = { version = "0.1", features = ["serde"] }
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
aho-corasick = "1.0.2"
js-sys = "0.3.51"
wasm-bindgen-futures = "0.4.24"
serde_derive = "^1.0.59"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'console',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
