server_hostname = "127.0.0.1:8000"
api_endpoint="http://localhost:8000/api"

[profiles.rocksdb]
type = "rocksdb"
datadir = "/tmp/terraphim_rocksdb"

[profiles.redb]
type = "redb"
path = "/tmp/terraphim_redb"

[profiles.sqlite]
type = "sqlite"
connection_string = "/tmp/terraphim_sqlite.db"

[profiles.dash]
type = "dashmap"
root = "/tmp/terraphim_dash"

[profiles.memory]
type = "memory"