server_hostname = "${TERRAPHIM_SERVER_HOSTNAME:-127.0.0.1:8000}"
api_endpoint = "${TERRAPHIM_SERVER_API_ENDPOINT:-http://localhost:8000/api}"
initialized = "${TERRAPHIM_INITIALIZED:-false}"
default_data_path = "${TERRAPHIM_DATA_PATH:-${HOME}/.terraphim}"

[profiles.sled]
type = "sled"
datadir = "/tmp/opendal/sled"

[profiles.dash]
type = "dashmap"
root = "/tmp/dashmaptest"
