#!/bin/bash
# Tauri signing setup script for 1Password integration
# This script configures Tauri signing using 1Password stored credentials

set -euo pipefail

echo "🔐 Setting up Tauri signing with 1Password integration..."
echo ""

# Function to read from 1Password with fallback
read_1password_secret() {
    local secret_path="$1"
    local env_var_name="$2"
    local fallback_value="$3"
    
    echo "Reading $secret_path..."
    
    # Try to read from 1Password
    if command -v op > /dev/null && op account list > /dev/null 2>&1; then
        if secret_value=$(op read "$secret_path" 2>/dev/null | tr -d '\n' | tr -d '\r'); then
            echo "✅ Successfully read $secret_path from 1Password"
            export "$env_var_name"="$secret_value"
            return 0
        fi
    fi
    
    echo "⚠️ Could not read from 1Password, using fallback"
    export "$env_var_name"="$fallback_value"
    return 1
}

# Read Tauri signing keys from 1Password
echo "🔑 Reading Tauri signing keys..."

read_1password_secret "op://TerraphimPlatform/TauriSigning/TAURI_PRIVATE_KEY" "TAURI_PRIVATE_KEY" "TEMP_FALLBACK_PRIVATE_KEY"
read_1password_secret "op://TerraphimPlatform/TauriSigning/TAURI_PUBLIC_KEY" "TAURI_PUBLIC_KEY" "TEMP_FALLBACK_PUBLIC_KEY"
read_1password_secret "op://TerraphimPlatform/TauriSigning/credential" "TAURI_CREDENTIAL" "TEMP_FALLBACK_CREDENTIAL"

echo ""
echo "📋 Current Tauri signing environment:"
echo "TAURI_PRIVATE_KEY=${TAURI_PRIVATE_KEY:0:20}..."
echo "TAURI_PUBLIC_KEY=${TAURI_PUBLIC_KEY:0:20}..." 
echo "TAURI_CREDENTIAL=${TAURI_CREDENTIAL:0:20}..."

# Validate that we have the required keys
if [[ "$TAURI_PRIVATE_KEY" == "TEMP_FALLBACK_PRIVATE_KEY" ]]; then
    echo ""
    echo "⚠️ WARNING: Using fallback keys instead of 1Password"
    echo "Please ensure:"
    echo "1. You are signed into 1Password"
    echo "2. The 1Password vault 'TerraphimPlatform' exists"
    echo "3. The secret paths are correct"
    echo ""
    echo "To setup 1Password manually:"
    echo "  op signin --account my.1password.com"
    echo "  # Then run this script again"
fi

# Create/update .tauriconfig for local builds
echo ""
echo "🔧 Creating Tauri configuration..."

TAURI_CONFIG_DIR="$HOME/.tauri"
mkdir -p "$TAURI_CONFIG_DIR"

# Create signing configuration
cat > "$TAURI_CONFIG_DIR/tauriconfig" << EOF
# Tauri signing configuration
# Generated by setup-tauri-signing.sh

[signing]
private_key = $TAURI_PRIVATE_KEY
public_key = $TAURI_PUBLIC_KEY
credential = $TAURI_CREDENTIAL

[build]
beforeBuildCommand = yarn tauri sign --private-key "$TAURI_PRIVATE_KEY" --public-key "$TAURI_PUBLIC_KEY" --password "$TAURI_CREDENTIAL" && yarn build
EOF

echo "✅ Created $TAURI_CONFIG_DIR/tauriconfig"

# Update environment for current session
echo "🔐 Exporting signing variables for current session..."
export TAURI_PRIVATE_KEY
export TAURI_PUBLIC_KEY  
export TAURI_CREDENTIAL

echo ""
echo "✅ Tauri signing setup complete!"
echo ""
echo "🚀 You can now build signed Tauri applications:"
echo "   cd desktop"
echo "   yarn tauri build --bundles deb rpm appimage"
echo ""
echo "🔐 Keys will be automatically used for signing during builds."