VERSION --try --global-cache 0.7
PROJECT applied-knowledge-systems/terraphim-project
IMPORT github.com/earthly/lib/rust AS rust
FROM ubuntu:24.04

ARG TARGETARCH
ARG TARGETOS
ARG TARGETPLATFORM
ARG --global tag=$TARGETOS-$TARGETARCH
ARG --global TARGETARCH
IF [ "$TARGETARCH" = amd64 ]
    ARG --global ARCH=x86_64
ELSE
    ARG --global ARCH=$TARGETARCH
END

WORKDIR /code

pipeline:
  BUILD +fmt
  BUILD +lint
  BUILD +test
  BUILD +build


install:
  FROM ubuntu:24.04
  ENV DEBIAN_FRONTEND=noninteractive
  ENV DEBCONF_NONINTERACTIVE_SEEN=true
  RUN apt-get update -qq
  RUN apt-get install -yqq --no-install-recommends build-essential ca-certificates curl musl-tools musl-dev
  RUN update-ca-certificates
  # Install Rust from official installer
  RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.76.0
  ENV PATH="/root/.cargo/bin:$PATH"
  ENV CARGO_HOME="/root/.cargo"
  RUN rustup component add clippy
  RUN rustup component add rustfmt
  RUN cargo install cross
  DO rust+INIT --keep_fingerprints=true

source:
  FROM +install
  COPY --keep-ts --dir . .
  DO rust+CARGO --args=fetch --keep-fingerprints=true
  SAVE ARTIFACT dist as LOCAL /dist

build:
  FROM +source
  DO rust+CARGO --args="build --offline --release" --output="release/[^/\.]+"
  RUN ./target/release/terraphim_server --version
  SAVE ARTIFACT ./target/release/terraphim_server AS LOCAL artifact/bin/terraphim_server-$TARGET

test:
  FROM +source
  DO rust+CARGO --args="test"

fmt:
  FROM +source
  DO rust+CARGO --args="fmt --check"

lint:
  FROM +source
  DO rust+CARGO --args="clippy --no-deps --all-features --all-targets"

save-fe-local:
  COPY ./dist ./dist
  SAVE ARTIFACT ./dist AS LOCAL ./dist
