base_url = "https://terraphim.ai"
title = "Terraphim AI"
description = "Privacy-Preserving AI Assistant"
theme = "WarpDrive"
default_language = "en"
output_dir = "public"
compile_sass = false
minify_html = false
ignored_content = []
generate_feeds = true
feed_filenames = ["rss.xml"]
hard_link_static = false

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

build_search_index = true

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[link_checker]
skip_prefixes = [
    "http://[2001:db8::]/",
]

skip_anchor_prefixes = [
    "https://caniuse.com/",
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[translations]

[languages]

[extra]
version = "1.16.0"

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/posts", name = "Posts" },
        { url = "https://docs.terraphim.ai", name = "Docs" },
        { url = "$BASE_URL/tags", name = "Tags" },
        { url = "$BASE_URL/categories", name = "Categories" },
        { url = "$BASE_URL/docs/donate", name = "Donate" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Dr Alexander Mikhalev"
avatar = "images/terraphim_logo_gray.png"

[extra.social]
github = "terraphim"
linkedin = "alexmikhalev"
email = "alex@terraphim.ai"
twitter = "alex_mikhalev"
discord = "VPJXB6BGuY"
reddit = "TerraphimAI"

[extra.analytics]
google = "G-5KRW51RLEJ"
