name: Frontend Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '18'
      cache-key:
        description: 'Cache key for dependencies'
        required: false
        type: string
    outputs:
      dist-path:
        description: 'Path to built frontend dist'
        value: ${{ jobs.build.outputs.dist-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Further increased timeout for frontend builds
    outputs:
      dist-path: ${{ steps.build.outputs.dist-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: desktop/package-lock.json

      - name: Cache node modules and npm cache
        uses: actions/cache@v4
        with:
          path: |
            desktop/node_modules
            ~/.npm
          key: ${{ inputs.cache-key }}-npm-${{ inputs.node-version }}-${{ hashFiles('desktop/package-lock.json') }}
          restore-keys: |
            ${{ inputs.cache-key }}-npm-${{ inputs.node-version }}-
            ${{ inputs.cache-key }}-npm-

      - name: Set environment variables for CI
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          npm_config_legacy_peer_deps: true
          npm_config_cache: ~/.npm-cache
        run: |
          echo "Environment variables set for CI build"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq --no-install-recommends \
            python3 \
            make \
            g++ \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm2 \
            libxkbcommon-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libxss-dev \
            libasound2-dev

      - name: Run frontend build and tests
        run: ./scripts/ci-check-frontend.sh

      - name: Set dist path output
        id: build
        run: |
          if [[ -d desktop/dist ]]; then
            echo "Frontend build completed successfully"
            echo "dist-path=desktop/dist" >> $GITHUB_OUTPUT
          else
            echo "Frontend build failed, creating fallback"
            mkdir -p desktop/dist
            echo '<html><body><h1>Build Failed</h1></body></html>' > desktop/dist/index.html
            echo "dist-path=desktop/dist" >> $GITHUB_OUTPUT
          fi

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: desktop/dist
          retention-days: 30

      - name: Verify build output
        run: |
          ls -la desktop/dist
          echo "Frontend build completed successfully"
