name: Frontend Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        type: string
        default: '18'
      cache-key:
        description: 'Cache key for dependencies'
        required: false
        type: string
    outputs:
      dist-path:
        description: 'Path to built frontend dist'
        value: ${{ jobs.build.outputs.dist-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.build.outputs.dist-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
          cache-dependency-path: desktop/yarn.lock
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: desktop/node_modules
          key: ${{ inputs.cache-key }}-node-${{ inputs.node-version }}-${{ hashFiles('desktop/package.json') }}
          restore-keys: |
            ${{ inputs.cache-key }}-node-${{ inputs.node-version }}-
            ${{ inputs.cache-key }}-node-

      - name: Run frontend build and tests
        run: ./scripts/ci-check-frontend.sh

      - name: Set dist path output
        id: build
        run: |
          if [[ -d desktop/dist ]]; then
            echo "Frontend build completed successfully"
            echo "dist-path=desktop/dist" >> $GITHUB_OUTPUT
          else
            echo "Frontend build failed, creating fallback"
            mkdir -p desktop/dist
            echo '<html><body><h1>Build Failed</h1></body></html>' > desktop/dist/index.html
            echo "dist-path=desktop/dist" >> $GITHUB_OUTPUT
          fi

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: desktop/dist
          retention-days: 30

      - name: Verify build output
        run: |
          ls -la desktop/dist
          echo "Frontend build completed successfully"
