[package]
name = "test_signature"
version = "0.2.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
base64 = "0.21.0"
ed25519-dalek = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_jcs = "0.1.0"
