VERSION --cache-persist-option --global-cache 0.7
PROJECT applied-knowledge-systems/terraphim-project
FROM ghcr.io/terraphim/terraphim_builder_native:latest

WORKDIR frontend

deps:
    # COPY package.json tsconfig.json yarn.lock vite.config.ts tsconfig.node.json index.html ./
    COPY --keep-ts . .
    # COPY --dir src src
    # COPY --dir public public
    RUN oro apply
    RUN pkgx +yarnpkg.com yarn

build:
    FROM +deps
    RUN pkgx +yarnpkg.com yarn run build
    SAVE ARTIFACT dist /dist AS LOCAL dist