VERSION --cache-persist-option --global-cache 0.7
PROJECT applied-knowledge-systems/terraphim-project
FROM ghcr.io/terraphim/terraphim_builder_native:latest

WORKDIR /code/desktop

deps:
    # COPY package.json tsconfig.json yarn.lock vite.config.ts tsconfig.node.json index.html ./
    COPY --keep-ts . .
    # COPY --dir src src
    # COPY --dir public public
    RUN oro apply -q || true
    RUN /code/desktop/scripts/yarn_and_build.sh

build:
    FROM +deps
    # RUN pkgx +yarnpkg.com yarn run build

    SAVE ARTIFACT dist /dist AS LOCAL dist